package CorbaApp;


/**
* CorbaApp/ValuesGetterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ValuesGetter.idl
* Thursday, 13 April 2017 21:01:19 o'clock GMT+03:00
*/

public interface ValuesGetterOperations 
{
  String getValues (int a);
  void shutdown ();
} // interface ValuesGetterOperations
