package CorbaApp;


/**
* CorbaApp/ValuesGetterPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ValuesGetter.idl
* Thursday, 13 April 2017 21:01:19 o'clock GMT+03:00
*/

public abstract class ValuesGetterPOA extends org.omg.PortableServer.Servant
 implements CorbaApp.ValuesGetterOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getValues", new java.lang.Integer (0));
    _methods.put ("shutdown", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CorbaApp/ValuesGetter/getValues
       {
         int a = in.read_long ();
         String $result = null;
         $result = this.getValues (a);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // CorbaApp/ValuesGetter/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CorbaApp/ValuesGetter:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ValuesGetter _this() 
  {
    return ValuesGetterHelper.narrow(
    super._this_object());
  }

  public ValuesGetter _this(org.omg.CORBA.ORB orb) 
  {
    return ValuesGetterHelper.narrow(
    super._this_object(orb));
  }


} // class ValuesGetterPOA
