package CorbaApp;


/**
* CorbaApp/ValuesGetterHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ValuesGetter.idl
* Thursday, 13 April 2017 21:02:02 o'clock GMT+03:00
*/

abstract public class ValuesGetterHelper
{
  private static String  _id = "IDL:CorbaApp/ValuesGetter:1.0";

  public static void insert (org.omg.CORBA.Any a, CorbaApp.ValuesGetter that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CorbaApp.ValuesGetter extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (CorbaApp.ValuesGetterHelper.id (), "ValuesGetter");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CorbaApp.ValuesGetter read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ValuesGetterStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CorbaApp.ValuesGetter value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static CorbaApp.ValuesGetter narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CorbaApp.ValuesGetter)
      return (CorbaApp.ValuesGetter)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CorbaApp._ValuesGetterStub stub = new CorbaApp._ValuesGetterStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static CorbaApp.ValuesGetter unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CorbaApp.ValuesGetter)
      return (CorbaApp.ValuesGetter)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CorbaApp._ValuesGetterStub stub = new CorbaApp._ValuesGetterStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
