package CorbaApp;


/**
* CorbaApp/ValuesGetter.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ValuesGetter.idl
* Thursday, 13 April 2017 21:02:02 o'clock GMT+03:00
*/

public interface ValuesGetter extends ValuesGetterOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ValuesGetter
